### ISSUE TITLE
Timeout: No Response

### ISSUE THREAD

**Issue by kelups** [Kalarumeth/Check-WatchGuard#2]
Hello again :)

Sorry for contacting you again but maybe you can help me.  First of all: I think the new version of your check is better :) I definitely like it.

So the check works every 5 minutes all day long, but we have the problem that we get the message "Timeout: No Response" 2-3 times a day. I can't figure out why the watchguard reacts like that. Maybe you've seen something like this before.

In my opinion: it blocks any SNMP request for a certain time.

Thanks in advance.

**Comment by Kalarumeth** [comment]
Welcome back! I'm glad you like my script :D

To understand the problem I ask you some of questions:

Is host checked on lan?
Trying with prompt it give back timeout?
Which check give back timeout?
Have any policy on Firewall to block snmp?

I know your issue, some time the check give me back 'timeout' but only on remote host.

You can try this, on line 61 there is a core snmpwalk function you can add next to version add -r for set the number of retries and -t for set the request timeout (in seconds), for example if add these "-r 1 -t 5", you can be obtain 10 seconds for time out.

You could try this and let me know if it worked I would add it to the script:

```
...

Source.SNMP() {
    snmpwalk -v $SNMPVERSION -r 1 -t 10 -Oe -c $COMMUNITY $HOST_NAME $1
}

...
```

FYI: Default timeout of snmpwalk is 1

**Comment by kelups** [comment]
Hi there,
Sorry for the late reply.

To answer your questions:
Yes, the host is checked internally in a LAN (also via cable).
Yes, a timeout is also issued via cmd.
All checks return a timeout.
No, we don't have a policy that blocks snmp.

I've included your idea with the retries. We also noticed that the IP of the monitoring server has changed => that's why the wrong IP was saved in the WatchGuard. Since the correct IP was added: it works again without problems. 

So the topic has been resolved for now. 

Other topic: do you know how to visualize the WatchGuard checks in Grafana? I can access and visualize the data from most of the checks. But I don't know how to get the data on checks with multiple arguments like your checks. 

Thank you for your help.

**Comment by Kalarumeth** [comment]
Hi there,
great that you solved the problem, when I wrote the script I didn't think of integrating it with Grafana, in my master I use it and Grafana is an excellent resource. My knowledge in Grafana is very limited, but I will try to find a way to integrate the script. I believe we can close this issue and eventually open one just for Watchguard Graphs.
